apiVersion: v1
kind: Service
metadata:
  name: authentication-api-headless
  namespace: authentication-api
spec:
  clusterIP: None
  ports:
  - port: 8000
    targetPort: 8000
    name: authentication-api
  selector:
    app: authentication-api