site_name: ChainFactory Documentation
theme:
  name: material
  # features:
  #   - header.autohide
markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc

# nav:
#   - Framework: framework.md
#   - sources: sources/

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/llxp
