loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    storageClassName: "standard"
  # fullnameOverride: "loki"


# promtail:
#   enabled: true
#   config:
#     lokiAddress: http://{{ .Release.Name }}:3100/loki/api/v1/push
#     snippets:
#       scrapeConfigs: |
#         - job_name: syslog
#           syslog:
#             listen_address: 0.0.0.0:1514
#             labels:
#               job: "syslog"
#           relabel_configs:
#           - source_labels: ['__syslog_message_hostname']
#             target_label: 'host'
#       syslogService:
#         enabled: true
#         type: ClusterIP
#         port: 1514

# fluent-bit:
#   enabled: false

grafana:
  enabled: true
  # sidecar:
  #   datasources:
  #     enabled: true
  #     maxLines: 1000
  # image:
  #   tag: 8.3.5

prometheus:
  enabled: true
  isDefault: false
  
  alertmanager:
    persistentVolume:
      enabled: true
      storageClassName: "standard"

  server:
    persistentVolume:
      enabled: true
      storageClassName: "standard"

# filebeat:
#   enabled: false
#   filebeatConfig:
#     filebeat.yml: |
#       # logging.level: debug
#       filebeat.inputs:
#       - type: container
#         paths:
#           - /var/log/containers/*.log
#         processors:
#         - add_kubernetes_metadata:
#             host: ${NODE_NAME}
#             matchers:
#             - logs_path:
#                 logs_path: "/var/log/containers/"
#       output.logstash:
#         hosts: ["logstash-loki:5044"]

# logstash:
#   enabled: false
#   fullnameOverride: "logstash-loki"
#   image: grafana/logstash-output-loki
#   imageTag: 1.0.1
#   filters:
#     main: |-
#       filter {
#         if [kubernetes] {
#           mutate {
#             add_field => {
#               "container_name" => "%{[kubernetes][container][name]}"
#               "namespace" => "%{[kubernetes][namespace]}"
#               "pod" => "%{[kubernetes][pod][name]}"
#             }
#             replace => { "host" => "%{[kubernetes][node][name]}"}
#           }
#         }
#         mutate {
#           remove_field => ["tags"]
#         }
#       }
#   outputs:
#     main: |-
#       output {
#         loki {
#           url => "http://loki:3100/loki/api/v1/push"
#           #username => "test"
#           #password => "test"
#         }
#         # stdout { codec => rubydebug }
#       }
