apiVersion: v1
kind: Secret
metadata:
  name: rest-api-secret
  namespace: rest-api
stringData:
  # generate using openssl rand -hex 32
  server-secret: "3102f570b3d490dfc500edde74c3633f4f2cceda3d8e39799221e124cd7e5649"
  # change in production to the actual mongodb url, change username and password to the actual mongodb username and password
  mongodb-url: "mongodb://my-admin:Start123@example-mongodb-0.example-mongodb-svc.mongodb-operator.svc.cluster.local:27017/db?authSource=admin&directConnection=true&serverSelectionTimeoutMS=2000"
  # change in production to the actual redis url, change password to the actual redis password
  redis-url: "redis://:0f5f194dab910259@redis-0.redis-headless.redis.svc.cluster.local:6379"
  # change in production to the actual idp admin username
  idp-username: "Administrator@example.org"
  # change in production to the actual idp admin password
  idp-password: "Start123"
  # change in production to the actual rabbitmq management user
  rabbitmq-management-user: "rest-api"
  # change in production to the actual rabbitmq management password
  rabbitmq-management-pass: "Start123"
  # change in production to the actual rabbitmq url, change username and password to the actual ones
  rabbitmq-url: "amqp://rest-api:Start123@rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cluster.local:5672"
type: Generic