apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: mongodb-operator
spec:
  schedule: "0 23 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: bitnami/mongodb:5.0.8-debian-10-r10
            command: ['/bin/sh', '-c', 'd=$(date -d "today" +"%Y%m%d%H%M") && mkdir -p /backup/$d && mongodump --uri=${MONGODB_URL} --out /backup/$d']
            env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-url
                  optional: false
            volumeMounts:
              - name: mongodb-backup-volume
                mountPath: /backup
          restartPolicy: Never
          volumes:
            - name: mongodb-backup-volume
              persistentVolumeClaim:
                claimName: mongodb-backup-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi