apiVersion: v1
data:
  # mongodb-url: "mongodb://my-admin:Start123@example-mongodb-0.example-mongodb-svc.mongodb-operator.svc.cluster.local:27017/db?authSource=admin&directConnection=true&serverSelectionTimeoutMS=200"
  mongodb-url: bW9uZ29kYjovL215LWFkbWluOlN0YXJ0MTIzQGV4YW1wbGUtbW9uZ29kYi0wLmV4YW1wbGUtbW9uZ29kYi1zdmMubW9uZ29kYi1vcGVyYXRvci5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9kYj9hdXRoU291cmNlPWFkbWluJmRpcmVjdENvbm5lY3Rpb249dHJ1ZSZzZXJ2ZXJTZWxlY3Rpb25UaW1lb3V0TVM9MjAw
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb-operator
type: Opaque