apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: redis
spec:
  # clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  - port: 8081
    targetPort: 8081
    name: redis-commander
  selector:
    app: redis