apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: samba-dc
  namespace: ldap
spec:
  selector:
    matchLabels:
      app: samba-dc
  serviceName: samba-dc
  volumeClaimTemplates:
  - metadata:
      name: samba-data
      namespace: ldap
    spec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "3Gi"
  - metadata:
      name: samba-config
      namespace: ldap
    spec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "1Gi"
  template:
    metadata:
      name: samba-dc
      namespace: ldap
      labels:
        app: samba-dc
    spec:
      initContainers:
      - name: "samba-create-fs-image"
        image: ubuntu:22.04
        command:
        - sh
        - -c
        - >-
          dd if=/dev/zero of=/mnt/ext4fs.img bs=1G count=0 seek=10 &&
          mkfs.ext4 /mnt/ext4fs.img
        volumeMounts:
          - name: samba-data
            mountPath: /mnt/
        securityContext:
          runAsUser: 0
          readOnlyRootFilesystem: false
      containers:
      - name: samba-dc
        image: mtr.external.otc.telekomcloud.com/llxp/chain-factory-dc:1.0.0
        imagePullPolicy: "Always"
        command: ["/bin/bash"]
        args:
        - -c
        - >-
            LOOP_DEVICE=$(losetup -fP --show ${VOLUME_MOUNT_TARGET}/ext4fs.img) &&
            mount ${LOOP_DEVICE} ${VOLUME_MOUNT_TARGET} &&
            printf "%s\n" "umount ${LOOP_DEVICE}" "losetup -d ${LOOP_DEVICE}" > pre-stop.sh &&
            chmod +x pre-stop.sh &&
            /init.sh setup
        securityContext:
          runAsUser: 0
          privileged: true
        env:
          - name: DOMAIN
            value: "example.org"
          - name: DOMAINPASS
            valueFrom:
              secretKeyRef:
                name: samba-dc-secret
                key: domainpass
                optional: false
          - name: INSECURELDAP
            value: "true"
          - name: VOLUME_MOUNT_TARGET
            value: "/var/lib/samba"  # this is the volume mount target, where the created image will be mounted
        ports:
          - name: tcp-ldap
            containerPort: 389
            protocol: TCP
          - name: ldap-udp
            containerPort: 389
            protocol: UDP
          - name: ldaps
            containerPort: 636
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: tcp-ldap
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 20
        readinessProbe:
          tcpSocket:
            port: tcp-ldap
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 20
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 100m
            memory: 1Gi
        volumeMounts:
          # - name: localtime
          #   mountPath: /etc/localtime
          #   readOnly: true
          - name: samba-data
            mountPath: /var/lib/samba
            readOnly: false
          - name: samba-config
            mountPath: /etc/samba/external
            readOnly: false
      volumes:
        # - name: localtime
        #   hostPath:
        #     path: /etc/localtime
        - name: samba-data
          persistentVolumeClaim:
            claimName: samba-data
        - name: samba-config
          persistentVolumeClaim:
            claimName: samba-config
