apiVersion: v1
kind: Service
metadata:
  name: samba-dc
  namespace: ldap
  labels:
    app: samba-dc
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 389
      targetPort: tcp-ldap
      protocol: TCP
    - name: udp-ldap
      port: 389
      targetPort: udp-ldap
      protocol: UDP
    - name: tcp-ldaps
      port: 636
      targetPort: tcp-ldaps
      protocol: TCP
  selector:
    app: samba-dc